/**
 * Abiquo community edition
 * cloud management application for hybrid clouds
 * Copyright (C) 2008-2010 - Abiquo Holdings S.L.
 *
 * This application is free software; you can redistribute it and/or
 * modify it under the terms of the GNU LESSER GENERAL PUBLIC
 * LICENSE as published by the Free Software Foundation under
 * version 3 of the License
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * LESSER GENERAL PUBLIC LICENSE v.3 for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.02 at 03:37:41 PM CET 
//


package com.abiquo.commons.amqp.impl.datacenter.domain.jobs;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VirtualMachine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirtualMachine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="machineID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hardwareConf" type="{http://abiquo.com/tarantino/model/jobs}HardwareConf"/>
 *         &lt;element name="networkConf">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="virtualNIC" type="{http://abiquo.com/tarantino/model/jobs}VirtualNIC" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="primaryDisk">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="DiskStandardConf">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DiskStandard" type="{http://abiquo.com/tarantino/model/jobs}DiskStandard"/>
 *                             &lt;element name="destinationDatastore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="diskStatefull" type="{http://abiquo.com/tarantino/model/jobs}DiskStatefull"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="secondaryDisks">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="auxDisk" type="{http://abiquo.com/tarantino/model/jobs}AuxDisk" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualMachine", propOrder = {
    "machineID",
    "hardwareConf",
    "networkConf",
    "primaryDisk",
    "secondaryDisks"
})
public class VirtualMachine {

    @XmlElement(required = true)
    protected String machineID;
    @XmlElement(required = true)
    protected HardwareConf hardwareConf;
    @XmlElement(required = true)
    protected VirtualMachine.NetworkConf networkConf;
    @XmlElement(required = true)
    protected VirtualMachine.PrimaryDisk primaryDisk;
    @XmlElement(required = true)
    protected VirtualMachine.SecondaryDisks secondaryDisks;

    /**
     * Gets the value of the machineID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineID() {
        return machineID;
    }

    /**
     * Sets the value of the machineID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineID(String value) {
        this.machineID = value;
    }

    /**
     * Gets the value of the hardwareConf property.
     * 
     * @return
     *     possible object is
     *     {@link HardwareConf }
     *     
     */
    public HardwareConf getHardwareConf() {
        return hardwareConf;
    }

    /**
     * Sets the value of the hardwareConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link HardwareConf }
     *     
     */
    public void setHardwareConf(HardwareConf value) {
        this.hardwareConf = value;
    }

    /**
     * Gets the value of the networkConf property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualMachine.NetworkConf }
     *     
     */
    public VirtualMachine.NetworkConf getNetworkConf() {
        return networkConf;
    }

    /**
     * Sets the value of the networkConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualMachine.NetworkConf }
     *     
     */
    public void setNetworkConf(VirtualMachine.NetworkConf value) {
        this.networkConf = value;
    }

    /**
     * Gets the value of the primaryDisk property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualMachine.PrimaryDisk }
     *     
     */
    public VirtualMachine.PrimaryDisk getPrimaryDisk() {
        return primaryDisk;
    }

    /**
     * Sets the value of the primaryDisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualMachine.PrimaryDisk }
     *     
     */
    public void setPrimaryDisk(VirtualMachine.PrimaryDisk value) {
        this.primaryDisk = value;
    }

    /**
     * Gets the value of the secondaryDisks property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualMachine.SecondaryDisks }
     *     
     */
    public VirtualMachine.SecondaryDisks getSecondaryDisks() {
        return secondaryDisks;
    }

    /**
     * Sets the value of the secondaryDisks property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualMachine.SecondaryDisks }
     *     
     */
    public void setSecondaryDisks(VirtualMachine.SecondaryDisks value) {
        this.secondaryDisks = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="virtualNIC" type="{http://abiquo.com/tarantino/model/jobs}VirtualNIC" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "virtualNIC"
    })
    public static class NetworkConf {

        protected List<VirtualNIC> virtualNIC;

        /**
         * Gets the value of the virtualNIC property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the virtualNIC property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVirtualNIC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VirtualNIC }
         * 
         * 
         */
        public List<VirtualNIC> getVirtualNIC() {
            if (virtualNIC == null) {
                virtualNIC = new ArrayList<VirtualNIC>();
            }
            return this.virtualNIC;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="DiskStandardConf">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DiskStandard" type="{http://abiquo.com/tarantino/model/jobs}DiskStandard"/>
     *                   &lt;element name="destinationDatastore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="diskStatefull" type="{http://abiquo.com/tarantino/model/jobs}DiskStatefull"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diskStandardConf",
        "diskStatefull"
    })
    public static class PrimaryDisk {

        @XmlElement(name = "DiskStandardConf")
        protected VirtualMachine.PrimaryDisk.DiskStandardConf diskStandardConf;
        protected DiskStatefull diskStatefull;

        /**
         * Gets the value of the diskStandardConf property.
         * 
         * @return
         *     possible object is
         *     {@link VirtualMachine.PrimaryDisk.DiskStandardConf }
         *     
         */
        public VirtualMachine.PrimaryDisk.DiskStandardConf getDiskStandardConf() {
            return diskStandardConf;
        }

        /**
         * Sets the value of the diskStandardConf property.
         * 
         * @param value
         *     allowed object is
         *     {@link VirtualMachine.PrimaryDisk.DiskStandardConf }
         *     
         */
        public void setDiskStandardConf(VirtualMachine.PrimaryDisk.DiskStandardConf value) {
            this.diskStandardConf = value;
        }

        /**
         * Gets the value of the diskStatefull property.
         * 
         * @return
         *     possible object is
         *     {@link DiskStatefull }
         *     
         */
        public DiskStatefull getDiskStatefull() {
            return diskStatefull;
        }

        /**
         * Sets the value of the diskStatefull property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiskStatefull }
         *     
         */
        public void setDiskStatefull(DiskStatefull value) {
            this.diskStatefull = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DiskStandard" type="{http://abiquo.com/tarantino/model/jobs}DiskStandard"/>
         *         &lt;element name="destinationDatastore" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "diskStandard",
            "destinationDatastore"
        })
        public static class DiskStandardConf {

            @XmlElement(name = "DiskStandard", required = true)
            protected DiskStandard diskStandard;
            @XmlElement(required = true)
            protected String destinationDatastore;

            /**
             * Gets the value of the diskStandard property.
             * 
             * @return
             *     possible object is
             *     {@link DiskStandard }
             *     
             */
            public DiskStandard getDiskStandard() {
                return diskStandard;
            }

            /**
             * Sets the value of the diskStandard property.
             * 
             * @param value
             *     allowed object is
             *     {@link DiskStandard }
             *     
             */
            public void setDiskStandard(DiskStandard value) {
                this.diskStandard = value;
            }

            /**
             * Gets the value of the destinationDatastore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDestinationDatastore() {
                return destinationDatastore;
            }

            /**
             * Sets the value of the destinationDatastore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDestinationDatastore(String value) {
                this.destinationDatastore = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="auxDisk" type="{http://abiquo.com/tarantino/model/jobs}AuxDisk" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "auxDisk"
    })
    public static class SecondaryDisks {

        protected List<AuxDisk> auxDisk;

        /**
         * Gets the value of the auxDisk property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the auxDisk property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuxDisk().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AuxDisk }
         * 
         * 
         */
        public List<AuxDisk> getAuxDisk() {
            if (auxDisk == null) {
                auxDisk = new ArrayList<AuxDisk>();
            }
            return this.auxDisk;
        }

    }

}
