//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.18 at 12:55:00 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://abiquo.com/virtualfactory/model/jobs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNSET)
package com.abiquo.virtualfactory.model.jobs;
