//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.18 at 11:15:04 AM CET 
//


package com.abiquo.virtualfactory.model.jobs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SnapshootVirtualMachine_IN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SnapshootVirtualMachine_IN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hypervisorConnection" type="{http://abiquo.com/virtualfactory/model/jobs}HypervisorConnection"/>
 *         &lt;element name="sourceDisk">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="diskStandard" type="{http://abiquo.com/virtualfactory/model/jobs}DiskStandard"/>
 *                   &lt;element name="diskStatefull" type="{http://abiquo.com/virtualfactory/model/jobs}DiskStandard"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="destinationDisk" type="{http://abiquo.com/virtualfactory/model/jobs}DiskStandard"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnapshootVirtualMachine_IN", propOrder = {
    "hypervisorConnection",
    "sourceDisk",
    "destinationDisk"
})
public class SnapshootVirtualMachineIN {

    @XmlElement(required = true)
    protected HypervisorConnection hypervisorConnection;
    @XmlElement(required = true)
    protected SnapshootVirtualMachineIN.SourceDisk sourceDisk;
    @XmlElement(required = true)
    protected DiskStandard destinationDisk;

    /**
     * Gets the value of the hypervisorConnection property.
     * 
     * @return
     *     possible object is
     *     {@link HypervisorConnection }
     *     
     */
    public HypervisorConnection getHypervisorConnection() {
        return hypervisorConnection;
    }

    /**
     * Sets the value of the hypervisorConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HypervisorConnection }
     *     
     */
    public void setHypervisorConnection(HypervisorConnection value) {
        this.hypervisorConnection = value;
    }

    /**
     * Gets the value of the sourceDisk property.
     * 
     * @return
     *     possible object is
     *     {@link SnapshootVirtualMachineIN.SourceDisk }
     *     
     */
    public SnapshootVirtualMachineIN.SourceDisk getSourceDisk() {
        return sourceDisk;
    }

    /**
     * Sets the value of the sourceDisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnapshootVirtualMachineIN.SourceDisk }
     *     
     */
    public void setSourceDisk(SnapshootVirtualMachineIN.SourceDisk value) {
        this.sourceDisk = value;
    }

    /**
     * Gets the value of the destinationDisk property.
     * 
     * @return
     *     possible object is
     *     {@link DiskStandard }
     *     
     */
    public DiskStandard getDestinationDisk() {
        return destinationDisk;
    }

    /**
     * Sets the value of the destinationDisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiskStandard }
     *     
     */
    public void setDestinationDisk(DiskStandard value) {
        this.destinationDisk = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="diskStandard" type="{http://abiquo.com/virtualfactory/model/jobs}DiskStandard"/>
     *         &lt;element name="diskStatefull" type="{http://abiquo.com/virtualfactory/model/jobs}DiskStandard"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diskStandard",
        "diskStatefull"
    })
    public static class SourceDisk {

        protected DiskStandard diskStandard;
        protected DiskStandard diskStatefull;

        /**
         * Gets the value of the diskStandard property.
         * 
         * @return
         *     possible object is
         *     {@link DiskStandard }
         *     
         */
        public DiskStandard getDiskStandard() {
            return diskStandard;
        }

        /**
         * Sets the value of the diskStandard property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiskStandard }
         *     
         */
        public void setDiskStandard(DiskStandard value) {
            this.diskStandard = value;
        }

        /**
         * Gets the value of the diskStatefull property.
         * 
         * @return
         *     possible object is
         *     {@link DiskStandard }
         *     
         */
        public DiskStandard getDiskStatefull() {
            return diskStatefull;
        }

        /**
         * Sets the value of the diskStatefull property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiskStandard }
         *     
         */
        public void setDiskStatefull(DiskStandard value) {
            this.diskStatefull = value;
        }

    }

}
