//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.02 at 03:37:41 PM CET 
//


package com.abiquo.tarantino.model.jobs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateVirtualMachine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateVirtualMachine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hypervisorConnection" type="{http://abiquo.com/tarantino/model/jobs}HypervisorConnection"/>
 *         &lt;element name="virtualMahine" type="{http://abiquo.com/tarantino/model/jobs}VirtualMachine"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateVirtualMachine", propOrder = {
    "hypervisorConnection",
    "virtualMahine"
})
public class CreateVirtualMachine {

    @XmlElement(required = true)
    protected HypervisorConnection hypervisorConnection;
    @XmlElement(required = true)
    protected VirtualMachine virtualMahine;

    /**
     * Gets the value of the hypervisorConnection property.
     * 
     * @return
     *     possible object is
     *     {@link HypervisorConnection }
     *     
     */
    public HypervisorConnection getHypervisorConnection() {
        return hypervisorConnection;
    }

    /**
     * Sets the value of the hypervisorConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HypervisorConnection }
     *     
     */
    public void setHypervisorConnection(HypervisorConnection value) {
        this.hypervisorConnection = value;
    }

    /**
     * Gets the value of the virtualMahine property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualMachine }
     *     
     */
    public VirtualMachine getVirtualMahine() {
        return virtualMahine;
    }

    /**
     * Sets the value of the virtualMahine property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualMachine }
     *     
     */
    public void setVirtualMahine(VirtualMachine value) {
        this.virtualMahine = value;
    }

}
