//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.02 at 03:37:41 PM CET 
//


package com.abiquo.tarantino.model.jobs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HypervisorConnection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HypervisorConnection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hypervisorID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hypervisortype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loginUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loginPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HypervisorConnection", propOrder = {
    "hypervisorID",
    "hypervisortype",
    "ip",
    "port",
    "protocol",
    "loginUser",
    "loginPassword"
})
public class HypervisorConnection {

    @XmlElement(required = true)
    protected String hypervisorID;
    @XmlElement(required = true)
    protected String hypervisortype;
    @XmlElement(required = true)
    protected String ip;
    @XmlElement(required = true)
    protected String port;
    @XmlElement(required = true)
    protected String protocol;
    @XmlElement(required = true)
    protected String loginUser;
    @XmlElement(required = true)
    protected String loginPassword;

    /**
     * Gets the value of the hypervisorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHypervisorID() {
        return hypervisorID;
    }

    /**
     * Sets the value of the hypervisorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHypervisorID(String value) {
        this.hypervisorID = value;
    }

    /**
     * Gets the value of the hypervisortype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHypervisortype() {
        return hypervisortype;
    }

    /**
     * Sets the value of the hypervisortype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHypervisortype(String value) {
        this.hypervisortype = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIp() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIp(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the loginUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginUser() {
        return loginUser;
    }

    /**
     * Sets the value of the loginUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginUser(String value) {
        this.loginUser = value;
    }

    /**
     * Gets the value of the loginPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * Sets the value of the loginPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginPassword(String value) {
        this.loginPassword = value;
    }

}
